version: '3.8'

# Docker Compose configuration for AI System Administrator Agent with Remote LLM
# Features: Remote Qwen3-4B-Thinking + API Gateway + Wiki.js
# Uses remote LLM service at http://100.79.227.126:1234

services:
  # API Gateway for remote LLM integration
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway.pi
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "4000:8080"  # Main API Gateway port
      - "4001:8081"  # Admin/Status port
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
    environment:
      - GATEWAY_HOST=0.0.0.0
      - GATEWAY_PORT=8080
      - ADMIN_PORT=8081
      - REMOTE_LLM_URL=http://100.79.227.126:1234
      - REMOTE_LLM_MODEL=qwen/qwen3-4b-thinking-2507
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
      - PYTHON_DONTWRITEBYTECODE=1
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    networks:
      - ai-agent-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Documentation website with API proxy
  docs:
    image: nginx:alpine
    container_name: ai-agent-docs
    restart: unless-stopped
    ports:
      - "3004:80"  # Map internal port 80 to external port 3004
    volumes:
      - ./website:/usr/share/nginx/html:ro
      - ./website/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ai-agent-network
    depends_on:
      - api-gateway
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  ai-agent-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ai-agent-br

volumes:
  wiki_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/inggo/ai-agent/data/wiki
  wiki_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/inggo/ai-agent/logs/wiki
